apiVersion: v1
kind: Secret
metadata:
  name: shop-db-secrets
  namespace: polyglot-shop
type: Opaque
stringData:
  DB_USER: shopuser
  DB_PASSWORD: shoppass
  DB_HOST: postgres
  DB_PORT: "5432"
  DB_NAME: shopdb
  JWT_SECRET: secret
